# ===================================================================
# BẢN LƯU NHÁP CÁC CHUỖI BÍ MẬT DÀNH CHO MÔI TRƯỜNG CHẠY TRÊN MÁY TÍNH (LOCAL)
# CẢNH BÁO: BẠN PHẢI THÊM FILE NÀY VÀO .gitignore ĐỂ KHÔNG BỊ ĐẨY LÊN GITHUB!
# ===================================================================

# Mật khẩu Database
spring.datasource.password=Toilatien2k6

# Chữ ký Token JWT
jwt.secret=SmartBusJwtSuperSecretKey2026@SkyBus!VietNam#Secure

# Mật khẩu Email gửi vé
spring.mail.password=fbykymjogdnthqwq

# Khóa bí mật Google Đăng Nhập
google.client.secret=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

# Khóa API ngân hàng SePay
sepay.token=M2M5CO1H4ND6MK0YACOVST1AWEOLSVMFWEPSHP5PVIFC77AYV9XLQZLJUEYQZ4D2
