# ===================================================================
# SERVER CONFIGURATION
# ===================================================================
server.port=8080
server.servlet.context-path=/api

# ===================================================================
# DATASOURCE CONFIGURATION (PostgreSQL - Supabase Cloud)
# ===================================================================
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.dddedoqabjjsckviqdhe
spring.datasource.password=Toilatien2k6

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA / HIBERNATE CONFIGURATION
# ===================================================================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# JWT CONFIGURATION
# ===================================================================
# Secret key: Chuoi bi mat de ky token (phai dai hon 256-bit = 32 ky tu)
jwt.secret=SmartBusJwtSuperSecretKey2026@SkyBus!VietNam#Secure
# Token het han sau 7 ngay (7 * 24 * 60 * 60 * 1000 ms)
jwt.expiration-ms=604800000

# ===================================================================
# EMAIL CONFIGURATION (SMTP)
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tienvuive2006@gmail.com
spring.mail.password=fbykymjogdnthqwq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===================================================================
# GOOGLE LOGIN (OAUTH2)
# ===================================================================
google.client.id=364596436412-glfi5lc4m0r787ds442edu1nnr6ioa87.apps.googleusercontent.com
google.client.secret=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

